TRANSLATIONS = {
    # ─── Navigation ─────────────────────────────────────────────
    "nav.home": "Home",
    "nav.pipeline": "Pipeline",
    "nav.kount": "\u03bcKount",
    "nav.detect": "\u03bcDetect",
    "nav.results": "Results",
    "nav.about": "Technical Details",
    "nav.cuora": "Cuora",
    "nav.future": "Future Features",
    "nav.disclaimer": "Disclaimer",
    "nav.acknowledgments": "Acknowledgments",
    "nav.faq": "FAQ",
    "nav.fundamentals": "Project Overview",

    # ─── Sidebar ────────────────────────────────────────────────
    "sidebar.language": "Language / Idioma",
    "sidebar.restart": "\U0001f504 Restart pipeline",
    "sidebar.microbiology_cta": "If you want to know more about microbiology:",
    "sidebar.microbiology_handle": "lifeisaboutmicrobiology",

    # ─── Home ───────────────────────────────────────────────────
    "home.title": "\u03bcKount&\u03bcDetect",
    "home.subtitle": "Artificial Intelligence for Agar Plate Analysis",
    "home.intro": "Computer vision system for:",
    "home.bullet.detection": "Colony Detection",
    "home.bullet.counting": "Automatic Counting",
    "home.bullet.classification": "Microbiological Classification",
    "home.based_on.intro": "Based on:",
    "home.based_on.kount": "\u03bcKount (YOLO) \u2014 Colony detection and counting",
    "home.based_on.detect": "\u03bcDetect (CNN) \u2014 Microbial species classification",
    "home.pipeline": "Visual Pipeline",
    "home.pipeline.upload.title": "Upload",
    "home.pipeline.upload.subtitle": "Image",
    "home.pipeline.kount.title": "\u03bcKount",
    "home.pipeline.kount.subtitle": "YOLO Detection",
    "home.pipeline.crop.title": "Crop & Prep",
    "home.pipeline.crop.subtitle": "Black Background",
    "home.pipeline.detect.title": "\u03bcDetect",
    "home.pipeline.detect.subtitle": "CNN Classification",
    "home.pipeline.results.title": "Results",
    "home.pipeline.results.subtitle": "Visualizations",
    "home.dataset": "AGAR Dataset",
    "home.dataset.images": "~18,000 agar plate images",
    "home.dataset.annotations": "~337,000 colony annotations",
    "home.dataset.configs": "Multiple capture setups and lighting conditions",
    "home.dataset.source": "Dataset: AGAR dataset by NeuroSYS Research",
    "home.dataset.authors": "Researchers: Majchrowska et al. (2021)",
    "home.dataset.title": "Title: AGAR a microbial colony dataset for deep learning detection",
    "home.supporting": (
        "Supporting microbiologists through automated colony detection, "
        "counting and preliminary colony classification."
    ),
    "home.whatis.title": "What is \u03bcKount & \u03bcDetect?",
    "home.whatis.content": (
        "\u03bcKount & \u03bcDetect is an Artificial Intelligence project developed "
        "as the final project of the **LABORLAN 2026: IA&Data Tech \u2013 "
        "Artificial Intelligence and Technology Project Management** programme.\n\n"
        "The application assists the **macroscopic analysis of microbial cultures** "
        "grown on agar plates by combining Computer Vision and Deep Learning techniques.\n\n"
        "It performs three main tasks:\n\n"
        "* \U0001f50d Automatic colony detection\n"
        "* \U0001f522 Automatic colony counting\n"
        "* \U0001f9eb Preliminary colony classification\n\n"
        "The classification provided by the model represents the **most compatible species "
        "based on colony morphology** and should be considered as decision support "
        "rather than a definitive microbiological identification."
    ),
    "home.architecture.title": "AI Architecture",
    "home.arch.kount": (
        "### \u03bcKount (YOLO)\n\nAutomatic colony detection and counting."
    ),
    "home.arch.detect": (
        "### \u03bcDetect (CNN)\n\nPreliminary microbial colony classification."
    ),
    "home.scope.title": "Model Scope",
    "home.scope.content": (
        "The current version has been trained using:\n\n"
        "* TSA agar plates\n"
        "* Top-view, high-resolution images\n"
        "* Five microbial species:\n\n"
        "  * _Bacillus subtilis_\n"
        "  * _Candida albicans_\n"
        "  * _Escherichia coli_\n"
        "  * _Pseudomonas aeruginosa_\n"
        "  * _Staphylococcus aureus_\n\n"
        "Predictions outside these conditions may be unreliable."
    ),
    "home.dataset.content": (
        "Approximately **18,000 agar plate images** and **337,000 colony annotations** "
        "from multiple acquisition setups and lighting conditions.\n\n"
        "Dataset: **AGAR Dataset** (Majchrowska et al., 2021)"
    ),
    "home.notice.title": "Scientific Notice",
    "home.notice.items": (
        "\u03bcKount & \u03bcDetect is currently a **Proof of Concept**.\n\n"
        "The results generated by this application:\n\n"
        "* are intended exclusively for research and educational purposes;\n"
        "* do not constitute a microbiological or clinical diagnosis;\n"
        "* do not replace standard laboratory identification techniques;\n"
        "* should always be interpreted by qualified personnel;\n"
        "* require confirmation using conventional microbiological methods "
        "(e.g. biochemical tests or MALDI-TOF)."
    ),

    # ─── Pipeline page ──────────────────────────────────────────
    "pipeline.title": "\U0001f52c Processing Pipeline",
    "pipeline.show_tutorial": "\U0001f4a1 Show tutorial",
    "pipeline.tutorial.title": "Step-by-step guide",
    "pipeline.tutorial.0": "**Upload an agar plate image** \u2014 The process "
        "starts when you upload a photo of an agar plate. The app accepts "
        "standard formats like PNG, JPG, and JPEG. Once loaded, the image "
        "is stored in memory and ready for the next step.",
    "pipeline.tutorial.1": "**\u03bcKount (YOLO detection)** \u2014 \u03bcKount uses a YOLOv8 "
        "model to scan the image and locate every colony. For each colony found, "
        "it draws a bounding box and assigns a confidence score. You can review "
        "the results before proceeding.",
    "pipeline.tutorial.2": "**Bounding boxes** \u2014 Each detected colony is "
        "highlighted with a coloured box and a number. The confidence level (0\u20131) "
        "tells you how sure the model is that it found a real colony. Higher is better.",
    "pipeline.tutorial.3": "**Crop extraction** \u2014 Each bounding box is used to cut "
        "out a small square from the original image, isolating a single colony. "
        "These crops are the input for the next phase.",
    "pipeline.tutorial.4": "**Black background** \u2014 A filter removes the bright agar "
        "background, leaving only the colony visible against black. This helps "
        "the CNN focus on the colony's shape and texture, improving classification accuracy.",
    "pipeline.tutorial.5": "**\u03bcDetect (CNN classification)** \u2014 Each black-background "
        "crop is passed through a MobileNetV2 model that predicts the most likely "
        "species. The result includes a probability for all 5 supported species.",
    "pipeline.tutorial.6": "**Results & interpretation** \u2014 The final page shows: "
        "a species distribution chart, per-colony probabilities, a heatmap, and "
        "detailed cards for each species. **Remember**: this is a proof of concept "
        "\u2014 results must be verified in a laboratory.",
    "pipeline.subtitle": "Complete \u03bcKount&\u03bcDetect flow diagram, from original image to final classification.",
    "pipeline.step1.title": "\U0001f4e4 Input Image",
    "pipeline.step1.desc": "The user uploads an agar plate image (PNG, JPG, JPEG). "
        "The image is converted to RGB and stored for processing.",
    "pipeline.step1.source": "services/preprocessing_service.py",
    "pipeline.step2.title": "\U0001f50d \u03bcKount (YOLO)",
    "pipeline.step2.desc": "YOLO-based detection model (You Only Look Once). "
        "Locates colonies in the image generating bounding boxes with associated confidence. "
        "Returns coordinates and confidence score for each detected colony.",
    "pipeline.step2.source": "services/detection_service.py",
    "pipeline.step3.title": "\U0001f4e6 Bounding Boxes",
    "pipeline.step3.desc": "Detected colonies are displayed with colored bounding boxes on the original image. "
        "Each box includes a numeric identifier and the detection confidence level.",
    "pipeline.step3.source": "detection_service.py \u2192 components/image_viewer.py",
    "pipeline.step4.title": "\u2702\ufe0f Crop Extraction",
    "pipeline.step4.desc": "Each detected colony is individually extracted from the original image "
        "using its bounding box coordinates. Crops are prepared for the classification phase.",
    "pipeline.step4.source": "services/preprocessing_service.py",
    "pipeline.step5.title": "\u2b1b Black Background",
    "pipeline.step5.desc": "A black background filter is applied to each crop: pixels with value "
        "above a threshold (light agar background) are converted to black, "
        "keeping only the colony visible. This improves CNN accuracy.",
    "pipeline.step5.source": "services/preprocessing_service.py",
    "pipeline.step6.title": "\U0001f9ea \u03bcDetect (CNN)",
    "pipeline.step6.desc": "CNN model based on Transfer Learning. Each black-background crop is classified "
        "into one of 5 supported species, returning a probability vector for each.",
    "pipeline.step6.source": "services/classification_service.py",
    "pipeline.step7.title": "\U0001f4ca Prediction + Results",
    "pipeline.step7.desc": "Final results: species distribution, per-colony metrics, "
        "probability map and interactive visualizations with Plotly.",
    "pipeline.step7.source": "pages/05_results.py + components/charts.py",

    # ─── μKount page ───────────────────────────────────────────
    "kount.title": "\U0001f50d \u03bcKount \u2014 Colony Detection",
    "kount.subtitle": "YOLO-based colony detection with Slicing Aided Hyper Inference.",
    "kount.tab.upload": "Upload Image",
    "kount.tab.examples": "Example Images",
    "kount.upload.label": "Select an agar plate image",
    "kount.status.loaded": "Image loaded successfully.",
    "kount.examples.select": "Select an example image below to load it:",
    "kount.examples.none": "No example images found.",
    "kount.download_json": "\U0001f4e5 Download JSON",
    "kount.confidence.label": "Detection confidence threshold",
    "kount.filter.label": "Minimum confidence to display",
    "kount.detect.button": "\u25b6\ufe0f Run \u03bcKount",
    "kount.status.detected": "{count} colonies detected in {time} s.",
    "kount.next.button": "\u27a1\ufe0f Process with \u03bcDetect",
    "kount.no_image": "Upload an image to start.",
    "kount.loaded_image": "Loaded image",
    "kount.detection_result": "Detection result",
    "kount.detection_mode.title": "Detection Mode",
    "kount.detection_mode.full": "\u26a1 Vibrio Mode (Recommended)",
    "kount.detection_mode.sahi": "\U0001f50d Agar Explorer Mode",
    "kount.detection_mode.full.desc": "Fast whole-plate detection.",
    "kount.detection_mode.sahi.desc": "High-resolution detection for dense plates.",
    "kount.detection_mode.sahi.optimizing": "\u26a0\ufe0f Optimization in progress \u2014 optimizing for better output quality",
    "kount.upload.guide.title": "📤 Upload images for μKount",
    "kount.upload.guide.desc": "Before uploading, make sure your images are **high quality and well-focused**.",
    "kount.upload.guide.example": "🔎 Example Google search:",
    "kount.upload.guide.example_query": "agar plate triptona soya agar",
    "kount.upload.guide.search_button": "🔍 Google Images",
    "kount.upload.guide.tip_size": "📏 Image size: **Large**",
    "kount.upload.guide.tip_clarity": "🧫 Clear Petri dish / agar visibility",
    "kount.upload.guide.tip_compression": "📸 No heavy compression",

    # ─── μDetect page ──────────────────────────────────────────
    "detect.title": "\U0001f9ea \u03bcDetect \u2014 Colony Classification",
    "detect.subtitle": "Classifies each detected colony by microbial species.",
    "detect.warning.no_detections": "No previous detections. Run \u03bcKount first "
        "to detect colonies in an image.",
    "detect.button.back": "\u2190 Go to \u03bcKount",
    "detect.error.no_image": "No original image available. Go back to \u03bcKount and load an image.",
    "detect.status.ready": "{count} colonies detected ready for classification.",
    "detect.process.button": "\u25b6\ufe0f Run \u03bcDetect",
    "detect.step1.title": "Crop Extraction",
    "detect.step1.desc": "Extracting each colony from the original image using bounding box coordinates...",
    "detect.step2.title": "Black Background",
    "detect.step2.desc": "Applying black background to each crop to improve classification...",
    "detect.status.crops_extracted": "{count} crops extracted.",
    "detect.status.classified": "{count} colonies classified.",
    "detect.toast.done": "Done! You have {count} colonies, the main ones are: {species}",
    "detect.results.title": "Results per colony",
    "detect.colony.label": "Colony #{number}",
    "detect.colony.processed": "Processed crop",
    "detect.species.label": "Predicted species",
    "detect.confidence.label": "Confidence",
    "detect.detection_precision": "Detection precision",
    "detect.probabilities.title": "View detailed probabilities",
    "detect.info.run": "Press 'Run \u03bcDetect' to classify the colonies.",
    "detect.button.results": "\U0001f4ca Go to Results",
    "detect.mode.title": "Classification Mode",
    "detect.mode.flash": "\u26a1 Flash (Fast)",
    "detect.mode.robust": "\U0001f9ea Robust (Multimodal)",
    "detect.mode.flash.desc": "Fast classification using CNN only (current default).",
    "detect.mode.robust.desc": "Precise classification using plate detection + multimodal CNN with area data.",
    "detect.step.plate": "Plate Detection & Measurement",
    "detect.warning.plate_not_found": "Plate not detected. Falling back to Flash mode.",
    "detect.status.fallback": "Falling back to Flash mode...",
    "detect.mm_per_pixel": "Scale (mm/pixel)",
    "detect.plate_debug": "Detected plate contour",

    # ─── Results page ───────────────────────────────────────────
    "results.title": "\U0001f4ca Results \u2014 Global Results",
    "results.subtitle": "Complete summary of the agar plate analysis.",
    "results.warning.no_data": "No analysis data available. Run \u03bcKount and \u03bcDetect first.",
    "results.summary.title": "Analysis Summary",
    "results.species_distribution.title": "Species Distribution",
    "results.percentage.title": "Percentage Distribution",
    "results.probability_table.title": "Probabilities per Colony",
    "results.probability_map.title": "Probability Map",
    "results.species_info.title": "Detected Species Information",
    "results.no_classifications": "No classifications available. Run \u03bcDetect to classify the detected colonies.",
    "results.colony": "Colony",
    "results.predicted_species": "Predicted species",
    "results.description": "Description",
    "results.clinical_significance": "Clinical significance",
    "results.industrial_relevance": "Industrial relevance",
    "results.pharmaceutical_applications": "Pharmaceutical applications",
    "results.common_habitats": "Common habitats",
    "results.warnings": "Warnings",
    "results.biosafety_notes": "Biosafety",
    "results.references": "References",
    "results.not_available": "N/A",
    "results.download_json": "\U0001f4e5 Download JSON",
    "results.download_pdf": "\U0001f4c4 Download PDF",
    "results.tab.kount": "\u03bcKount",
    "results.tab.detect": "\u03bcDetect",
    "results.cfu.title": "\U0001f9ee CFU Calculator",
    "results.cfu.subtitle": "Estimate the microbial concentration of the original sample from the detected colony count.",
    "results.cfu.colony_count": "Colony count",
    "results.cfu.sample_type": "Sample type",
    "results.cfu.liquid": "Liquid sample",
    "results.cfu.solid": "Solid sample",
    "results.cfu.dilution": "Dilution",
    "results.cfu.volume": "Plated volume (mL)",
    "results.cfu.calculate": "\U0001f9ee Calculate CFU",
    "results.cfu.result": "Estimated concentration",
    "results.cfu.unit_ml": "CFU/mL",
    "results.cfu.unit_g": "CFU/g",
    "results.cfu.error.colonies": "Colony count must be greater than 0.",
    "results.cfu.error.volume": "Volume must be greater than 0.",
    "results.cfu.error.dilution": "Please select a dilution.",
    "results.cfu.validation.valid": "\U0001f7e2 Valid count (30\u2013300 colonies). Suitable for CFU estimation.",
    "results.cfu.validation.low": "\U0001f7e1 Low colony count (<30). Estimation may be inaccurate.",
    "results.cfu.validation.high": "\U0001f534 Too numerous to count (>300 colonies). Consider using a higher dilution.",
    "results.cfu.disclaimer": "This estimation is based on the detected colony count and the dilution parameters provided by the user. Results are intended for educational and research purposes and should always be confirmed using standard microbiological laboratory procedures.",

    # ─── About page ────────────────────────────────────────────
    "about.title": "\u2699\ufe0f Technical Details",
    "about.subtitle": "\u03bcKount&\u03bcDetect (Artificial Intelligence for Agar Plate Analysis) is a "
        "computer vision system designed for detection, counting and classification of "
        "microbial colonies on agar plates. "
        "This project is the final capstone project of the Laborlan training program in AI, Machine Learning and Deep Learning",
    "about.kount.title": "\U0001f9eb \u03bcKount \u2014 Colony Detector",
    "about.kount.function": "Locate colonies in agar plate images, "
        "generate bounding boxes around each colony, "
        "provide automatic colony counting.",
    "about.kount.tech": "Architecture: YOLOv8, Framework: Ultralytics, "
        "Output format: coordinates (x1, y1, x2, y2) + confidence",
    "about.detect.title": "\U0001f9ea \u03bcDetect \u2014 Species Classifier",
    "about.detect.function": "Classify individual colonies into microbial species, "
        "provide probabilities for each supported species.",
    "about.detect.species": "*S. aureus, B. subtilis, P. aeruginosa, E. coli, C. albicans*",
    "about.detect.tech": "Architecture: CNN based on pre-trained models (MobileNet), "
        "Framework: TensorFlow / PyTorch (to be defined)",
    "about.dataset.title": "\U0001f4ca AGAR Dataset",
    "about.dataset.content": "~18,000 agar plate images, ~337,000 individual colony annotations, "
        "Multiple capture setups (lighting, angle, distance), "
        "Annotations by expert microbiologists. "
        "Images were acquired under controlled laboratory conditions "
        "and represent 5 different microbial species.",
    "about.env.title": "\u2699\ufe0f Development Environment",
    "about.env.content": "Python 3.11, Streamlit 1.38+, Ultralytics YOLOv8, "
        "TensorFlow 2.15, OpenCV 4.9, NumPy, Plotly, scikit-learn",
    "about.training.title": "\U0001f9e0 Model Training",
    "about.training.kount": "**\u03bcKount (YOLOv8m)** \u2014 Input: 640px, "
        "Epochs: 150, Batch: 16, Optimizer: AdamW, Hardware: NVIDIA RTX 3060 12GB",
    "about.training.detect": "**\u03bcDetect (MobileNetV2)** \u2014 Input: 224px, "
        "Transfer Learning, Species: 5, Epochs: 50, Framework: TensorFlow",
    "about.paper.title": "\U0001f4c4 Academic Reference",
    "about.paper.content": "Majchrowska et al. (2021). AGAR: a microbial colony "
        "dataset for deep learning detection. *Scientific Reports*, 11, 23973. "
        "DOI: [10.1038/s41598-021-02912-2](https://doi.org/10.1038/s41598-021-02912-2)",
    "about.repository.title": "\U0001f4bb Source Code",
    "about.repository.content": "The full source code of this project is available at:\n\n"
        "[https://github.com/eguzki-dm/agar-web](https://github.com/eguzki-dm/agar-web)",
    "about.architecture.title": "Project Architecture",

    # ─── Future Features page ───────────────────────────────────
    "future.title": "\U0001f680 Future Features",
    "future.subtitle": "Implemented and planned features for \u03bcKount&\u03bcDetect.",
    "future.feature.edit_boxes": "Edit bounding boxes",
    "future.feature.edit_boxes.desc": "Move, resize, delete or add detection boxes manually "
        "after \u03bcKount processing.",
    "future.feature.optimize_sahi": "Optimize SAHI slicing processing",
    "future.feature.optimize_sahi.desc": "Improve performance of the SAHI sliced inference pipeline for dense agar plates. Optimize slice overlap, batch processing, and post-processing to reduce detection time while maintaining sensitivity for small colonies.",
    "future.feature.improve_cnn": "Improve CNN for bacteria classification",
    "future.feature.improve_cnn.desc": "Retrain the model with more species, varied culture "
        "media and lighting conditions to improve generalisation.",

    # ─── Disclaimer page ────────────────────────────────────────
    "disclaimer.title": "\u26a0\ufe0f Disclaimer \u2014 Ethical and Scientific Notice",
    "disclaimer.banner.title": "\u03bcKount&\u03bcDetect is a Proof-of-Concept Research System",
    "disclaimer.banner.text": "Must NOT be used for clinical diagnosis.",
    "disclaimer.limitations.title": "System Limitations",
    "disclaimer.limitation1.title": "\U0001f52c Purely research purpose",
    "disclaimer.limitation1.desc": "\u03bcKount&\u03bcDetect is a research and development tool. It is not approved "
        "by any health authority (FDA, EMA, etc.) for diagnostic use.",
    "disclaimer.limitation2.title": "\U0001f9ea Does not replace gold-standard techniques",
    "disclaimer.limitation2.desc": "Conventional microbiological methods (culture, Gram stain, "
        "biochemical tests, MALDI-TOF) remain the reference standard. "
        "\u03bcKount&\u03bcDetect does not replace these methods.",
    "disclaimer.limitation3.title": "\u26a0\ufe0f Experimental results",
    "disclaimer.limitation3.desc": "Detection and classification models can produce errors. "
        "False positives, false negatives and incorrect classifications are "
        "possible and must be verified.",
    "disclaimer.limitation4.title": "\U0001f4cb Validation required",
    "disclaimer.limitation4.desc": "All results must be validated through appropriate "
        "laboratory procedures before making any decisions.",
    "disclaimer.limitation5.title": "\U0001f468\u200d\U0001f52c Professional interpretation required",
    "disclaimer.limitation5.desc": "Results must be interpreted exclusively by qualified "
        "personnel (microbiologists, biochemists, healthcare professionals).",
    "disclaimer.limitation6.title": "\U0001f916 No clinical judgment",
    "disclaimer.limitation6.desc": "The system does not incorporate clinical judgment or "
        "contextual patient knowledge. It cannot consider medical history "
        "or other variables relevant to diagnosis.",
    "disclaimer.responsible_use.title": "Responsible Use",
    "disclaimer.responsible_use.intro": "By using \u03bcKount&\u03bcDetect, the user agrees to:",
    "disclaimer.responsible_use.item1": "NOT use the results for clinical diagnosis without prior validation.",
    "disclaimer.responsible_use.item2": "NOT make medical decisions based solely on the system output.",
    "disclaimer.responsible_use.item3": "Verify all detections and classifications through conventional methods.",
    "disclaimer.responsible_use.item4": "Cite \u03bcKount&\u03bcDetect as a research tool in any publication using its results.",
    "disclaimer.responsible_use.footer": "Failure to comply with these conditions may have serious consequences "
        "in clinical contexts. The developers of \u03bcKount&\u03bcDetect are not responsible "
        "for misuse of the system.",
    "disclaimer.version.title": "Current Version",
    "disclaimer.version.info": "Version 1.0.0 \u2014 Cuora is alive! \U0001f9e0",
    "disclaimer.version.desc": "This initial version uses simulated data to demonstrate the architecture "
        "and workflow. Real models (YOLO, CNN) will be integrated in later phases.",
    "disclaimer.version.status": "Status: Proof of Concept / Functional Prototype",

    # ─── Cards ──────────────────────────────────────────────────
    "cards.disclaimer.title": "\u26a0\ufe0f IMPORTANT \u2014 ETHICAL AND SCIENTIFIC NOTICE",
    "cards.disclaimer.poc": "\u03bcKount&\u03bcDetect is currently a Proof of Concept.",
    "cards.disclaimer.warning": "Results generated by the models:",
    "cards.disclaimer.item1": "Do not constitute clinical diagnosis.",
    "cards.disclaimer.item2": "Do not replace gold-standard microbiological techniques.",
    "cards.disclaimer.item3": "Must be validated through appropriate laboratory procedures.",
    "cards.disclaimer.item4": "Must be interpreted by qualified personnel.",
    "cards.disclaimer.footer": "Automatic classification may contain errors and should be considered "
        "solely as a decision support tool.",
    "cards.disclaimer.short": "\u26a0\ufe0f \u03bcKount&\u03bcDetect is a Proof-of-Concept research system. Results are experimental "
        "and must not be used for clinical diagnosis. Always validate through "
        "standard microbiological methods.",
    "cards.species.full_name": "Full name",
    "cards.species.gram": "Gram",
    "cards.species.shape": "Morphology",
    "cards.species.description": "View full description",
    "cards.species.not_available": "Not available.",
    "cards.future.planned": "planned",
    "cards.future.in_progress": "in_progress",
    "cards.future.completed": "completed",

    # ─── Charts ─────────────────────────────────────────────────
    "charts.distribution.title": "Species Distribution",
    "charts.distribution.x_label": "Species",
    "charts.distribution.y_label": "Number of colonies",
    "charts.heatmap.title": "Probability Map per Colony",
    "charts.heatmap.x_label": "Species",
    "charts.heatmap.y_label": "Colony",
    "charts.heatmap.color_label": "Probability",
    "charts.table.colony": "Colony",
    "charts.table.predicted": "Predicted species",
    "charts.metrics.detected": "Detected colonies",
    "charts.metrics.classified": "Classified colonies",
    "charts.metrics.time_kount": "\u03bcKount time",
    "charts.metrics.time_detect": "\u03bcDetect time",

    # ─── Acknowledgments page ─────────────────────────────────────
    "ack.title": "\U0001f64f Acknowledgments",
    "ack.program.title": "\U0001f393 Training Program",
    "ack.program.desc": "This project was developed as the final applied project within the "
        "**LABORLAN 2026: IA & Data Tech (Artificial Intelligence and Technology Project Management)** program.",
    "ack.mentor.title": "\U0001f9d1\u200d\U0001f3eb Mentor",
    "ack.mentor.desc": "Special thanks to **[Aitor Donado](https://github.com/Aitor-Donado)** for his "
        "technical guidance and continuous support throughout the project development.",
    "ack.classmates.title": "\U0001f465 Classmates",
    "ack.classmates.desc": "To all my classmates, who generously acted as Spark Worker Nodes "
        "to process my thousands of images. Thank you from the bottom of my heart! \u2665\ufe0f",
    "ack.dataset.title": "\U0001f4ca AGAR Dataset",
    "ack.dataset.desc": "Thanks to **Majchrowska et al.** and **NeuroSYS Research** for providing the AGAR dataset, "
        "which has been the fundamental basis for training and validating the detection and classification models.",
    "ack.patch.title": "\U0001f9e9 Patch Preprocessing",
    "ack.patch.desc": "To **Jarek Paw\u0142owski** for his [GitHub repository](https://github.com/jarek-pawlowski/microbial-dataset-generation) "
        "on microbial dataset generation, which served as a reference for implementing colony preprocessing and patching.",
    "ack.staff.title": "\U0001f3eb Teaching Staff and Organizers",
    "ack.staff.desc": "We thank the teaching staff, mentors, and organizers of LABORLAN 2026 for their commitment "
        "and the learning environment that made this project possible.",
    "cuora.title": "\U0001f9e0 Cuora",
    "cuora.subtitle": "Your virtual microbiologist \u2014 Only answers questions about bacteriology, virology, mycology, parasitology, immunology and molecular biology.",
    "cuora.chat_placeholder": "Ask about microbiology...",
    "cuora.login_title": "Sign in with your Google account to talk to Cuora",
    "cuora.login_button": "Continue with Google",
    "cuora.login_error": "GOOGLE_CLIENT_ID not configured in secrets.toml",
    "cuora.oauth_missing": "streamlit-oauth not installed. Using development mode.",
    "cuora.dev_mode": "Development mode \u2014 no real OAuth",
    "cuora.username_label": "Username",
    "cuora.dev_login": "Enter (dev)",
    "cuora.clear_chat": "\U0001f5d1\ufe0f Clear chat",
    "cuora.export": "\U0001f4be Export",
    "cuora.logout": "Logout",
    "cuora.api_key_error": "GROQ_API_KEY not found in secrets.toml. Configure it to use Cuora.",

    # ─── Project Overview ────────────────────────────────────────
    "fundamentals.title": "Project Overview",
    "fundamentals.welcome": (
        "Welcome to **\u03bcKount & \u03bcDetect**! This project is the final work "
        "of the **LABORLAN 2026: IA&Data Tech \u2013 Artificial Intelligence "
        "and Technology Project Management** programme.\n\n"
        "\u03bcKount & \u03bcDetect is a tool designed to assist in the **macroscopic analysis "
        "of microbial cultures**. In other words, it helps interpret what we observe "
        "with the naked eye on Petri dishes where samples with possible "
        "microorganisms have been cultured."
    ),
    "fundamentals.context.title": "Why is this important?",
    "fundamentals.context.content": (
        "When microorganisms grow on a culture plate, they form colonies, "
        "structures visible to the naked eye. Often these colonies must be counted, "
        "as their number allows estimating the Colony Forming Units (CFU) "
        "present in the original sample. This information is fundamental "
        "in multiple fields:"
    ),
    "fundamentals.industries": (
        "* **Food industry**, where the microbial load can help determine "
        "the shelf life of a product.\n"
        "* **Pharmaceutical industry**, to verify that a product meets the "
        "required microbiological criteria before commercialisation.\n"
        "* **Clinical microbiology**, where the CFU count can provide "
        "information about the severity of an infection.\n"
        "* **Water quality control**, where the presence of certain "
        "microorganisms, such as _Escherichia coli_, is unacceptable "
        "as it indicates faecal contamination."
    ),
    "fundamentals.classification.title": "Beyond counting",
    "fundamentals.classification.content": (
        "In addition to counting, colony classification is also important. "
        "Identifying which microorganism has grown provides valuable information. "
        "For example, detecting _Escherichia coli_ in a water sample indicates "
        "contamination requiring immediate action, while the presence of other "
        "microorganisms may be acceptable as long as established microbiological "
        "limits are not exceeded."
    ),
    "fundamentals.limitations.title": "Model Limitations",
    "fundamentals.limitations.content": (
        "For reliable results, it is important to note that the model has been "
        "trained with very specific images:\n\n"
        "* TSA (Tryptone Soya Agar) plates\n"
        "* Top-view photographs\n"
        "* High-resolution images\n"
        "* Colonies compatible only with the following species:\n\n"
        "  * _Bacillus subtilis_\n"
        "  * _Candida albicans_\n"
        "  * _Escherichia coli_\n"
        "  * _Pseudomonas aeruginosa_\n"
        "  * _Staphylococcus aureus_\n\n"
        "Therefore, this tool does not definitively identify microorganisms, "
        "but rather proposes the most compatible species based on the macroscopic "
        "appearance of the colony, always within the set of species it has been "
        "trained on. If images obtained under different culture conditions or "
        "belonging to different microorganisms are used, the results may not be correct."
    ),
    "fundamentals.support.title": "A Support, Not a Substitute",
    "fundamentals.support.content": (
        "It is important to remember that \u03bcKount & \u03bcDetect does not replace "
        "microbiological diagnosis performed in a laboratory.\n\n"
        "Microorganism identification usually requires a combination of different "
        "techniques, such as biochemical tests, metabolic assays, antigen analysis, "
        "and advanced instrumental methods, such as MALDI-TOF mass spectrometry. "
        "These techniques allow confirming the identity of the microorganism with "
        "high precision and, in many cases, determining its strain.\n\n"
        "\u03bcKount & \u03bcDetect should be understood as a **support tool for macroscopic "
        "colony analysis**. Its goal is to facilitate counting and provide an initial "
        "orientation on the possible identity of a colony based on its appearance. "
        "As new images, culture conditions, and species are incorporated into the "
        "model training, its usefulness and generalisation capacity will continue to grow.\n\n"
        "**Would you like to try it?**"
    ),
    "fundamentals.cuora_caption": "AI Assistant",
    "fundamentals.detection_strategies.title": "Detection Strategies",
    "fundamentals.detection_strategies.intro": "\u03bcKount offers two detection strategies that can be selected before running the analysis:",
    "fundamentals.detection_strategies.sahi": "**\U0001f52c SAHI + YOLO** \u2014 Designed for high-resolution images. Excellent for small colonies on dense agar plates. Uses image slicing to increase detection sensitivity.",
    "fundamentals.detection_strategies.full": "**\U0001f9eb Full Image YOLO** \u2014 Processes the complete image without slicing. Recommended for plates with few large colonies. Avoids duplications derived from slicing.",

    # ─── FAQ ─────────────────────────────────────────────────────
    "faq.title": "Frequently Asked Questions",
    "faq.q1.question": "What is \u03bcKount & \u03bcDetect?",
    "faq.q1.answer": (
        "\u03bcKount & \u03bcDetect is an AI-powered system for analyzing agar plates "
        "used in microbiology. \u03bcKount detects and counts microbial colonies using "
        "YOLO object detection, while \u03bcDetect classifies colony species using "
        "a CNN-based classifier."
    ),
    "faq.q2.question": "How does the pipeline work?",
    "faq.q2.answer": (
        "The pipeline consists of four stages: (1) upload an agar plate image "
        "or use an example image "
        "(the filename indicates the real colony count and species present, "
        "e.g. 17_ESCO.jpg = 17 E. coli colonies), "
        "(2) \u03bcKount detects and counts colonies with bounding boxes, "
        "(3) \u03bcDetect classifies each colony by species, "
        "(4) results are displayed in an interactive dashboard with charts and metrics."
    ),
    "faq.q3.question": "What is YOLO?",
    "faq.q3.answer": (
        "YOLO (You Only Look Once) is a real-time object detection algorithm. "
        "It divides the image into a grid and predicts bounding boxes and class probabilities "
        "in a single pass. \u03bcKount uses a YOLO model fine-tuned on the AGAR dataset "
        "for colony detection."
    ),
    "faq.q4.question": "What is a CNN?",
    "faq.q4.answer": (
        "A CNN (Convolutional Neural Network) is a deep learning architecture specialized "
        "for image analysis. \u03bcDetect uses a CNN trained to classify microbial species "
        "(S. aureus, E. coli, P. aeruginosa, B. subtilis, C. albicans) from colony crops."
    ),
    "faq.q5.question": "What image types can I upload?",
    "faq.q5.answer": (
        "You can upload PNG, JPG, and JPEG images of agar plates. "
        "The system also provides synthetic plate generation for testing purposes."
    ),
    "faq.q6.question": "How accurate are the results?",
    "faq.q6.answer": (
        "The detection model was trained on ~18,000 agar plate images with ~337,000 annotations "
        "from the AGAR dataset. Classification accuracy depends on image quality, lighting "
        "conditions, and colony morphology. Always validate results with traditional "
        "microbiological methods."
    ),
    "faq.q7.question": "Why is this tool important?",
    "faq.q7.answer": (
        "Manual colony counting and classification is time-consuming, subjective, and prone "
        "to human error. \u03bcKount & \u03bcDetect automates this process, providing "
        "consistent, fast, and reproducible results, accelerating microbiological analysis "
        "in clinical, industrial, and research settings."
    ),
    "faq.q8.question": "What do the abbreviations in the example files mean?",
    "faq.q8.answer": (
        "Example image filenames contain the colony count and species abbreviations:\n\n"
        "- ESCO = _Escherichia coli_\n"
        "- BASU = _Bacillus subtilis_\n"
        "- CAAL = _Candida albicans_\n"
        "- PSAE = _Pseudomonas aeruginosa_\n"
        "- STAU = _Staphylococcus aureus_"
    ),

    "cuora.analyzing": "\u23f3 Analyzing...",
    "cuora.default_name": "User",
    "cuora.prompt": (
        "You are an expert microbiologist with deep knowledge of bacteriology, "
        "virology, mycology, parasitology, immunology and molecular biology. "
        "You will ONLY answer questions related to microbiology. "
        "If the question is NOT about microbiology, answer exactly: "
        "'I'm sorry, I can only answer questions related to microbiology.' "
        "Do not make up information. If you do not know the answer, say so clearly. "
        "Always respond in the same language as the user."
    ),
}
